version: 2.1
# orbs:
#   coveralls: coveralls/coveralls@1.0.6

parameters:
  # This parameter is used to trigger the main workflow.
  trigger:
    type: boolean
    default: true

  # A parameter per packages
  core:
    type: boolean
    default: false

  nova:
    type: boolean
    default: false

  mongo-bundle:
    type: boolean
    default: false

  # Custom parameters
  # deploy:
  #   type: boolean
  #   default: false

executors:
  node:
    docker:
      - image: circleci/node:16.13.0
      - image: circleci/mongo:4.4.4

jobs:
  trigger-workflows:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          # This step is added to demonstrate the possibility to dynamically set the user token
          name: Set token
          command: echo "export CIRCLE_USER_TOKEN=${CIRCLE_USER_TOKEN}" >> $BASH_ENV
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/monorepo.sh && .circleci/monorepo.sh
          environment:
            # (optional) print additional debug information
            MONOREPO_DEBUG: "true"
            # (optional) additional CI parameters to include in the pipeline (must be a valid JSON)
            # CI_PARAMETERS: '{ "deploy": true }'

  test:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - checkout:
          path: ~/project
      # This step is added only to show that we are in the package directory
      - restore_cache:
          keys:
            - v2-npm-deps-<< parameters.package_name >>-{{ checksum "package.json" }}
            - v2-npm-deps-<< parameters.package_name >>-
      - run:
          name: Setup
          command: |
            npm install
      - save_cache:
          key: v2-npm-deps-<< parameters.package_name >>-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: |
            echo "Build << parameters.package_name >> ..."
            npm run test
      # - run:
      #     command: |
      #       npm run coverage
      # - coveralls/upload:
      #     verbose: true
      #     flag_name: << parameters.package_name >>
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/<< parameters.package_name >>

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  # Workflows defined for each package.

  core:
    when: << pipeline.parameters.core >>
    jobs:
      - test:
          name: core-test
          package_name: core

  nova:
    when: << pipeline.parameters.nova >>
    jobs:
      - test:
          name: nova-test
          package_name: nova
  mongo-bundle:
    when: << pipeline.parameters.mongo-bundle >>
    jobs:
      - test:
          name: mongo-bundle-test
          package_name: mongo-bundle
